name: "mednotes-api"

services:
    mednotes-api:
      profiles: ["api"]
      container_name: mednotes_api
      image: mednotes_api
      build: 
        context: .
        dockerfile: containers/Dockerfile.api

      restart: unless-stopped

      ports: 
        - 8000:8000

      entrypoint:
        [
          ".venv/bin/uvicorn",
          "--reload",
          "--host",
          "0.0.0.0",
          "--port",
          "8000",
          "--workers",
          "1",
          "mednotes.api.app:app"
        ]

      volumes:
      - "./backend/mednotes:/mednotes/mednotes"

    mednotes-db:
      profiles: ['api']
      container_name: mednotes_db
      image: postgres:17

      ports:
        - 5432:5432

      environment:
        POSTGRES_USER: johnwhitman
        POSTGRES_PASSWORD: password
        POSTGRES_DB: mednotes

      volumes:
        - "./data/postgres:/var/lib/postgresql/data"
    
