name: "mednotes-api"

services:
    mednotes-api:
      profiles: ["api"]
      container_name: mednotes_api
      image: mednotes_api
      build: 
        context: .
        dockerfile: containers/Dockerfile.api

      depends_on: 
        mednotes-db:
          condition: service_healthy

      restart: unless-stopped

      ports: 
        - 8000:8000

      entrypoint:
        [
          ".venv/bin/uvicorn",
          "--reload",
          "--host",
          "0.0.0.0",
          "--port",
          "8000",
          "--workers",
          "1",
          "mednotes.api.app:app"
        ]

      volumes:
      - "./backend/mednotes:/mednotes/mednotes"

    mednotes-db:
      profiles: ['api']
      container_name: mednotes_db
      image: ankane/pgvector:latest

      ports:
        - 5432:5432

      healthcheck:
        test: ["CMD-SHELL"]
        interval: 10s
        retries: 5
        start_period: 30s
        timeout: 10s

      environment:
        POSTGRES_USER: johnwhitman
        POSTGRES_PASSWORD: password
        POSTGRES_DB: mednotes

      volumes:
        - "./data/postgres:/var/lib/postgresql/data"
    
