name: "mednotes-api"

services:
    mednotes-api:
      profiles: ["api"]
      container_name: mednotes_api
      image: mednotes_api
      build: 
        context: .
        dockerfile: containers/Dockerfile.api

      restart: unless-stopped

      ports: 
        - 8000:8000

      entrypoint:
        [
          ".venv/bin/uvicorn",
          "--reload",
          "--host",
          "0.0.0.0",
          "--port",
          "8000",
          "--workers",
          "1",
          "mednotes.api.app:app"
        ]

      volumes:
      - "./backend/mednotes:/mednotes/mednotes"
    
