/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface AssetGet
 */
export interface AssetGet {
    /**
     * 
     * @type {number}
     * @memberof AssetGet
     */
    'asset_id': number;
    /**
     * 
     * @type {string}
     * @memberof AssetGet
     */
    'asset_path': string;
    /**
     * 
     * @type {boolean}
     * @memberof AssetGet
     */
    'compressed': boolean;
    /**
     * 
     * @type {string}
     * @memberof AssetGet
     */
    'description': string;
    /**
     * 
     * @type {number}
     * @memberof AssetGet
     */
    'size': number;
    /**
     * 
     * @type {string}
     * @memberof AssetGet
     */
    'type': string;
}
/**
 * 
 * @export
 * @interface EmbeddedSentenceEdit
 */
export interface EmbeddedSentenceEdit {
    /**
     * 
     * @type {number}
     * @memberof EmbeddedSentenceEdit
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof EmbeddedSentenceEdit
     */
    'text'?: string | null;
    /**
     * 
     * @type {Array<Topic>}
     * @memberof EmbeddedSentenceEdit
     */
    'topic'?: Array<Topic> | null;
}
/**
 * 
 * @export
 * @interface EmbeddedSentenceGet
 */
export interface EmbeddedSentenceGet {
    /**
     * 
     * @type {number}
     * @memberof EmbeddedSentenceGet
     */
    'note_id': number;
    /**
     * 
     * @type {string}
     * @memberof EmbeddedSentenceGet
     */
    'text': string;
    /**
     * 
     * @type {Array<Topic>}
     * @memberof EmbeddedSentenceGet
     */
    'topic'?: Array<Topic> | null;
}
/**
 * 
 * @export
 * @interface EmbeddedSentencePost
 */
export interface EmbeddedSentencePost {
    /**
     * 
     * @type {string}
     * @memberof EmbeddedSentencePost
     */
    'text': string;
    /**
     * 
     * @type {Array<Topic>}
     * @memberof EmbeddedSentencePost
     */
    'topic'?: Array<Topic> | null;
}
/**
 * 
 * @export
 * @interface HTTPValidationError
 */
export interface HTTPValidationError {
    /**
     * 
     * @type {Array<ValidationError>}
     * @memberof HTTPValidationError
     */
    'detail'?: Array<ValidationError>;
}
/**
 * 
 * @export
 * @interface LocationInner
 */
export interface LocationInner {
}
/**
 * 
 * @export
 * @interface PhotoAssetGet
 */
export interface PhotoAssetGet {
    /**
     * 
     * @type {number}
     * @memberof PhotoAssetGet
     */
    'asset_id': number;
    /**
     * 
     * @type {string}
     * @memberof PhotoAssetGet
     */
    'asset_path': string;
    /**
     * 
     * @type {boolean}
     * @memberof PhotoAssetGet
     */
    'compressed': boolean;
    /**
     * 
     * @type {string}
     * @memberof PhotoAssetGet
     */
    'description': string;
    /**
     * 
     * @type {string}
     * @memberof PhotoAssetGet
     */
    'format': string;
    /**
     * 
     * @type {number}
     * @memberof PhotoAssetGet
     */
    'size': number;
    /**
     * 
     * @type {string}
     * @memberof PhotoAssetGet
     */
    'type': string;
}
/**
 * 
 * @export
 * @interface QuestionEdit
 */
export interface QuestionEdit {
    /**
     * 
     * @type {string}
     * @memberof QuestionEdit
     */
    'answer'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof QuestionEdit
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof QuestionEdit
     */
    'text'?: string | null;
    /**
     * 
     * @type {Array<Topic>}
     * @memberof QuestionEdit
     */
    'topic'?: Array<Topic> | null;
}
/**
 * 
 * @export
 * @interface QuestionGet
 */
export interface QuestionGet {
    /**
     * 
     * @type {string}
     * @memberof QuestionGet
     */
    'answer': string;
    /**
     * 
     * @type {number}
     * @memberof QuestionGet
     */
    'question_id': number;
    /**
     * 
     * @type {string}
     * @memberof QuestionGet
     */
    'text': string;
    /**
     * 
     * @type {Array<Topic>}
     * @memberof QuestionGet
     */
    'topic'?: Array<Topic> | null;
}
/**
 * 
 * @export
 * @interface QuestionPost
 */
export interface QuestionPost {
    /**
     * 
     * @type {string}
     * @memberof QuestionPost
     */
    'answer': string;
    /**
     * 
     * @type {string}
     * @memberof QuestionPost
     */
    'text': string;
    /**
     * 
     * @type {Array<Topic>}
     * @memberof QuestionPost
     */
    'topic'?: Array<Topic> | null;
}
/**
 * 
 * @export
 * @enum {string}
 */

export const Topic = {
    General: 'general',
    Anatomy: 'anatomy',
    Biochemistry: 'biochemistry',
    Genetics: 'genetics',
    Immunology: 'immunology',
    Microbiology: 'microbiology',
    Pathology: 'pathology',
    Pharmacology: 'pharmacology',
    Anesthesiology: 'anesthesiology',
    Dermatology: 'dermatology',
    Emergency: 'emergency',
    Hospice: 'hospice',
    Cardiovascular: 'cardiovascular',
    Gastroenterology: 'gastroenterology',
    Hematology: 'hematology',
    Oncology: 'oncology',
    Nephrology: 'nephrology',
    InfectiousDisease: 'infectious disease',
    Rheumatology: 'rheumatology',
    Neurology: 'neurology',
    Obstetrics: 'obstetrics',
    Gynecology: 'gynecology',
    Ophthalmology: 'ophthalmology',
    Orthopaedics: 'orthopaedics',
    Otolaryngology: 'otolaryngology',
    Pediatrics: 'pediatrics',
    Plastics: 'plastics',
    PhysicalMedicineAndRehabilitation: 'physical medicine and rehabilitation',
    Psychiatry: 'psychiatry',
    Radiology: 'radiology',
    Surgery: 'surgery',
    Urology: 'urology'
} as const;

export type Topic = typeof Topic[keyof typeof Topic];


/**
 * 
 * @export
 * @interface Topic1
 */
export interface Topic1 {
}
/**
 * 
 * @export
 * @interface ValidationError
 */
export interface ValidationError {
    /**
     * 
     * @type {Array<LocationInner>}
     * @memberof ValidationError
     */
    'loc': Array<LocationInner>;
    /**
     * 
     * @type {string}
     * @memberof ValidationError
     */
    'msg': string;
    /**
     * 
     * @type {string}
     * @memberof ValidationError
     */
    'type': string;
}
/**
 * 
 * @export
 * @interface VolumeAssetGet
 */
export interface VolumeAssetGet {
    /**
     * 
     * @type {number}
     * @memberof VolumeAssetGet
     */
    'asset_id': number;
    /**
     * 
     * @type {string}
     * @memberof VolumeAssetGet
     */
    'asset_path': string;
    /**
     * 
     * @type {boolean}
     * @memberof VolumeAssetGet
     */
    'compressed': boolean;
    /**
     * 
     * @type {string}
     * @memberof VolumeAssetGet
     */
    'description': string;
    /**
     * 
     * @type {number}
     * @memberof VolumeAssetGet
     */
    'size': number;
    /**
     * 
     * @type {string}
     * @memberof VolumeAssetGet
     */
    'type': string;
}

/**
 * AssetApi - axios parameter creator
 * @export
 */
export const AssetApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create Asset
         * @param {string} description 
         * @param {File} file 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createAssetAssetCreateAssetPost: async (description: string, file: File, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'description' is not null or undefined
            assertParamExists('createAssetAssetCreateAssetPost', 'description', description)
            // verify required parameter 'file' is not null or undefined
            assertParamExists('createAssetAssetCreateAssetPost', 'file', file)
            const localVarPath = `/asset/create-asset`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();


            if (description !== undefined) { 
                localVarFormParams.append('description', description as any);
            }
    
            if (file !== undefined) { 
                localVarFormParams.append('file', file as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create Photo Asset
         * @param {string} description 
         * @param {File} file 
         * @param {string} format 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createPhotoAssetAssetCreatePhotoAssetPost: async (description: string, file: File, format: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'description' is not null or undefined
            assertParamExists('createPhotoAssetAssetCreatePhotoAssetPost', 'description', description)
            // verify required parameter 'file' is not null or undefined
            assertParamExists('createPhotoAssetAssetCreatePhotoAssetPost', 'file', file)
            // verify required parameter 'format' is not null or undefined
            assertParamExists('createPhotoAssetAssetCreatePhotoAssetPost', 'format', format)
            const localVarPath = `/asset/create-photo-asset`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();


            if (description !== undefined) { 
                localVarFormParams.append('description', description as any);
            }
    
            if (file !== undefined) { 
                localVarFormParams.append('file', file as any);
            }
    
            if (format !== undefined) { 
                localVarFormParams.append('format', format as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create Volume Asset
         * @param {string} description 
         * @param {File} file 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createVolumeAssetAssetCreateVolumeAssetPost: async (description: string, file: File, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'description' is not null or undefined
            assertParamExists('createVolumeAssetAssetCreateVolumeAssetPost', 'description', description)
            // verify required parameter 'file' is not null or undefined
            assertParamExists('createVolumeAssetAssetCreateVolumeAssetPost', 'file', file)
            const localVarPath = `/asset/create-volume-asset`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();


            if (description !== undefined) { 
                localVarFormParams.append('description', description as any);
            }
    
            if (file !== undefined) { 
                localVarFormParams.append('file', file as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete Photo Asset
         * @param {number} assetId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletePhotoAssetAssetPhotoAssetIdDelete: async (assetId: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'assetId' is not null or undefined
            assertParamExists('deletePhotoAssetAssetPhotoAssetIdDelete', 'assetId', assetId)
            const localVarPath = `/asset/photo/{asset_id}`
                .replace(`{${"asset_id"}}`, encodeURIComponent(String(assetId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Photo Asset
         * @param {number} assetId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPhotoAssetAssetPhotoAssetIdGet: async (assetId: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'assetId' is not null or undefined
            assertParamExists('getPhotoAssetAssetPhotoAssetIdGet', 'assetId', assetId)
            const localVarPath = `/asset/photo/{asset_id}`
                .replace(`{${"asset_id"}}`, encodeURIComponent(String(assetId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List Assets
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listAssetsAssetListAssetsGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/asset/list-assets`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AssetApi - functional programming interface
 * @export
 */
export const AssetApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AssetApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create Asset
         * @param {string} description 
         * @param {File} file 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createAssetAssetCreateAssetPost(description: string, file: File, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AssetGet>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createAssetAssetCreateAssetPost(description, file, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Create Photo Asset
         * @param {string} description 
         * @param {File} file 
         * @param {string} format 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createPhotoAssetAssetCreatePhotoAssetPost(description: string, file: File, format: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PhotoAssetGet>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createPhotoAssetAssetCreatePhotoAssetPost(description, file, format, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Create Volume Asset
         * @param {string} description 
         * @param {File} file 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createVolumeAssetAssetCreateVolumeAssetPost(description: string, file: File, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<VolumeAssetGet>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createVolumeAssetAssetCreateVolumeAssetPost(description, file, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Delete Photo Asset
         * @param {number} assetId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deletePhotoAssetAssetPhotoAssetIdDelete(assetId: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deletePhotoAssetAssetPhotoAssetIdDelete(assetId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get Photo Asset
         * @param {number} assetId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPhotoAssetAssetPhotoAssetIdGet(assetId: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPhotoAssetAssetPhotoAssetIdGet(assetId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary List Assets
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listAssetsAssetListAssetsGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<AssetGet>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listAssetsAssetListAssetsGet(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * AssetApi - factory interface
 * @export
 */
export const AssetApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AssetApiFp(configuration)
    return {
        /**
         * 
         * @summary Create Asset
         * @param {string} description 
         * @param {File} file 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createAssetAssetCreateAssetPost(description: string, file: File, options?: any): AxiosPromise<AssetGet> {
            return localVarFp.createAssetAssetCreateAssetPost(description, file, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create Photo Asset
         * @param {string} description 
         * @param {File} file 
         * @param {string} format 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createPhotoAssetAssetCreatePhotoAssetPost(description: string, file: File, format: string, options?: any): AxiosPromise<PhotoAssetGet> {
            return localVarFp.createPhotoAssetAssetCreatePhotoAssetPost(description, file, format, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create Volume Asset
         * @param {string} description 
         * @param {File} file 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createVolumeAssetAssetCreateVolumeAssetPost(description: string, file: File, options?: any): AxiosPromise<VolumeAssetGet> {
            return localVarFp.createVolumeAssetAssetCreateVolumeAssetPost(description, file, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete Photo Asset
         * @param {number} assetId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletePhotoAssetAssetPhotoAssetIdDelete(assetId: number, options?: any): AxiosPromise<void> {
            return localVarFp.deletePhotoAssetAssetPhotoAssetIdDelete(assetId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Photo Asset
         * @param {number} assetId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPhotoAssetAssetPhotoAssetIdGet(assetId: number, options?: any): AxiosPromise<any> {
            return localVarFp.getPhotoAssetAssetPhotoAssetIdGet(assetId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List Assets
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listAssetsAssetListAssetsGet(options?: any): AxiosPromise<Array<AssetGet>> {
            return localVarFp.listAssetsAssetListAssetsGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AssetApi - object-oriented interface
 * @export
 * @class AssetApi
 * @extends {BaseAPI}
 */
export class AssetApi extends BaseAPI {
    /**
     * 
     * @summary Create Asset
     * @param {string} description 
     * @param {File} file 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AssetApi
     */
    public createAssetAssetCreateAssetPost(description: string, file: File, options?: AxiosRequestConfig) {
        return AssetApiFp(this.configuration).createAssetAssetCreateAssetPost(description, file, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create Photo Asset
     * @param {string} description 
     * @param {File} file 
     * @param {string} format 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AssetApi
     */
    public createPhotoAssetAssetCreatePhotoAssetPost(description: string, file: File, format: string, options?: AxiosRequestConfig) {
        return AssetApiFp(this.configuration).createPhotoAssetAssetCreatePhotoAssetPost(description, file, format, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create Volume Asset
     * @param {string} description 
     * @param {File} file 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AssetApi
     */
    public createVolumeAssetAssetCreateVolumeAssetPost(description: string, file: File, options?: AxiosRequestConfig) {
        return AssetApiFp(this.configuration).createVolumeAssetAssetCreateVolumeAssetPost(description, file, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete Photo Asset
     * @param {number} assetId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AssetApi
     */
    public deletePhotoAssetAssetPhotoAssetIdDelete(assetId: number, options?: AxiosRequestConfig) {
        return AssetApiFp(this.configuration).deletePhotoAssetAssetPhotoAssetIdDelete(assetId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get Photo Asset
     * @param {number} assetId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AssetApi
     */
    public getPhotoAssetAssetPhotoAssetIdGet(assetId: number, options?: AxiosRequestConfig) {
        return AssetApiFp(this.configuration).getPhotoAssetAssetPhotoAssetIdGet(assetId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List Assets
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AssetApi
     */
    public listAssetsAssetListAssetsGet(options?: AxiosRequestConfig) {
        return AssetApiFp(this.configuration).listAssetsAssetListAssetsGet(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * MlApi - axios parameter creator
 * @export
 */
export const MlApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create Question
         * @param {QuestionPost} questionPost 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createQuestionMlQuestionPost: async (questionPost: QuestionPost, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'questionPost' is not null or undefined
            assertParamExists('createQuestionMlQuestionPost', 'questionPost', questionPost)
            const localVarPath = `/ml/question`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(questionPost, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete Note
         * @param {number} noteId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteNoteMlNoteDelete: async (noteId: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'noteId' is not null or undefined
            assertParamExists('deleteNoteMlNoteDelete', 'noteId', noteId)
            const localVarPath = `/ml/note`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (noteId !== undefined) {
                localVarQueryParameter['note_id'] = noteId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete Question
         * @param {number} questionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteQuestionMlQuestionDelete: async (questionId: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'questionId' is not null or undefined
            assertParamExists('deleteQuestionMlQuestionDelete', 'questionId', questionId)
            const localVarPath = `/ml/question`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (questionId !== undefined) {
                localVarQueryParameter['question_id'] = questionId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Edit Question
         * @param {QuestionEdit} questionEdit 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        editQuestionMlQuestionPut: async (questionEdit: QuestionEdit, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'questionEdit' is not null or undefined
            assertParamExists('editQuestionMlQuestionPut', 'questionEdit', questionEdit)
            const localVarPath = `/ml/question`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(questionEdit, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Edit Sentence
         * @param {EmbeddedSentenceEdit} embeddedSentenceEdit 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        editSentenceMlEditPut: async (embeddedSentenceEdit: EmbeddedSentenceEdit, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'embeddedSentenceEdit' is not null or undefined
            assertParamExists('editSentenceMlEditPut', 'embeddedSentenceEdit', embeddedSentenceEdit)
            const localVarPath = `/ml/edit`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(embeddedSentenceEdit, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Embed Sentence
         * @param {EmbeddedSentencePost} embeddedSentencePost 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        embedSentenceMlEmbedPost: async (embeddedSentencePost: EmbeddedSentencePost, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'embeddedSentencePost' is not null or undefined
            assertParamExists('embedSentenceMlEmbedPost', 'embeddedSentencePost', embeddedSentencePost)
            const localVarPath = `/ml/embed`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(embeddedSentencePost, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Search For Question
         * @param {string} searchKey 
         * @param {number} [resultRequest] 
         * @param {string | Array<string> | null} [stringArraystring] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchForQuestionMlSearchQuestionGet: async (searchKey: string, resultRequest?: number, stringArraystring?: string | Array<string> | null, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'searchKey' is not null or undefined
            assertParamExists('searchForQuestionMlSearchQuestionGet', 'searchKey', searchKey)
            const localVarPath = `/ml/search/question`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (searchKey !== undefined) {
                localVarQueryParameter['search_key'] = searchKey;
            }

            if (resultRequest !== undefined) {
                localVarQueryParameter['result_request'] = resultRequest;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(stringArraystring, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Search For Value
         * @param {string} searchSentence 
         * @param {number} [resultRequest] 
         * @param {Array<string> | null} [requestBody] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchForValueMlSearchNoteGet: async (searchSentence: string, resultRequest?: number, requestBody?: Array<string> | null, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'searchSentence' is not null or undefined
            assertParamExists('searchForValueMlSearchNoteGet', 'searchSentence', searchSentence)
            const localVarPath = `/ml/search/note`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (searchSentence !== undefined) {
                localVarQueryParameter['search_sentence'] = searchSentence;
            }

            if (resultRequest !== undefined) {
                localVarQueryParameter['result_request'] = resultRequest;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(requestBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MlApi - functional programming interface
 * @export
 */
export const MlApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MlApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create Question
         * @param {QuestionPost} questionPost 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createQuestionMlQuestionPost(questionPost: QuestionPost, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QuestionGet>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createQuestionMlQuestionPost(questionPost, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Delete Note
         * @param {number} noteId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteNoteMlNoteDelete(noteId: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteNoteMlNoteDelete(noteId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Delete Question
         * @param {number} questionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteQuestionMlQuestionDelete(questionId: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteQuestionMlQuestionDelete(questionId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Edit Question
         * @param {QuestionEdit} questionEdit 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async editQuestionMlQuestionPut(questionEdit: QuestionEdit, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QuestionGet>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.editQuestionMlQuestionPut(questionEdit, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Edit Sentence
         * @param {EmbeddedSentenceEdit} embeddedSentenceEdit 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async editSentenceMlEditPut(embeddedSentenceEdit: EmbeddedSentenceEdit, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EmbeddedSentenceGet>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.editSentenceMlEditPut(embeddedSentenceEdit, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Embed Sentence
         * @param {EmbeddedSentencePost} embeddedSentencePost 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async embedSentenceMlEmbedPost(embeddedSentencePost: EmbeddedSentencePost, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EmbeddedSentenceGet>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.embedSentenceMlEmbedPost(embeddedSentencePost, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Search For Question
         * @param {string} searchKey 
         * @param {number} [resultRequest] 
         * @param {string | Array<string> | null} [stringArraystring] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async searchForQuestionMlSearchQuestionGet(searchKey: string, resultRequest?: number, stringArraystring?: string | Array<string> | null, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<QuestionGet>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.searchForQuestionMlSearchQuestionGet(searchKey, resultRequest, stringArraystring, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Search For Value
         * @param {string} searchSentence 
         * @param {number} [resultRequest] 
         * @param {Array<string> | null} [requestBody] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async searchForValueMlSearchNoteGet(searchSentence: string, resultRequest?: number, requestBody?: Array<string> | null, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<EmbeddedSentenceGet>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.searchForValueMlSearchNoteGet(searchSentence, resultRequest, requestBody, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * MlApi - factory interface
 * @export
 */
export const MlApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MlApiFp(configuration)
    return {
        /**
         * 
         * @summary Create Question
         * @param {QuestionPost} questionPost 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createQuestionMlQuestionPost(questionPost: QuestionPost, options?: any): AxiosPromise<QuestionGet> {
            return localVarFp.createQuestionMlQuestionPost(questionPost, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete Note
         * @param {number} noteId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteNoteMlNoteDelete(noteId: number, options?: any): AxiosPromise<void> {
            return localVarFp.deleteNoteMlNoteDelete(noteId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete Question
         * @param {number} questionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteQuestionMlQuestionDelete(questionId: number, options?: any): AxiosPromise<void> {
            return localVarFp.deleteQuestionMlQuestionDelete(questionId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Edit Question
         * @param {QuestionEdit} questionEdit 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        editQuestionMlQuestionPut(questionEdit: QuestionEdit, options?: any): AxiosPromise<QuestionGet> {
            return localVarFp.editQuestionMlQuestionPut(questionEdit, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Edit Sentence
         * @param {EmbeddedSentenceEdit} embeddedSentenceEdit 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        editSentenceMlEditPut(embeddedSentenceEdit: EmbeddedSentenceEdit, options?: any): AxiosPromise<EmbeddedSentenceGet> {
            return localVarFp.editSentenceMlEditPut(embeddedSentenceEdit, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Embed Sentence
         * @param {EmbeddedSentencePost} embeddedSentencePost 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        embedSentenceMlEmbedPost(embeddedSentencePost: EmbeddedSentencePost, options?: any): AxiosPromise<EmbeddedSentenceGet> {
            return localVarFp.embedSentenceMlEmbedPost(embeddedSentencePost, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Search For Question
         * @param {string} searchKey 
         * @param {number} [resultRequest] 
         * @param {string | Array<string> | null} [stringArraystring] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchForQuestionMlSearchQuestionGet(searchKey: string, resultRequest?: number, stringArraystring?: string | Array<string> | null, options?: any): AxiosPromise<Array<QuestionGet>> {
            return localVarFp.searchForQuestionMlSearchQuestionGet(searchKey, resultRequest, stringArraystring, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Search For Value
         * @param {string} searchSentence 
         * @param {number} [resultRequest] 
         * @param {Array<string> | null} [requestBody] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchForValueMlSearchNoteGet(searchSentence: string, resultRequest?: number, requestBody?: Array<string> | null, options?: any): AxiosPromise<Array<EmbeddedSentenceGet>> {
            return localVarFp.searchForValueMlSearchNoteGet(searchSentence, resultRequest, requestBody, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MlApi - object-oriented interface
 * @export
 * @class MlApi
 * @extends {BaseAPI}
 */
export class MlApi extends BaseAPI {
    /**
     * 
     * @summary Create Question
     * @param {QuestionPost} questionPost 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MlApi
     */
    public createQuestionMlQuestionPost(questionPost: QuestionPost, options?: AxiosRequestConfig) {
        return MlApiFp(this.configuration).createQuestionMlQuestionPost(questionPost, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete Note
     * @param {number} noteId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MlApi
     */
    public deleteNoteMlNoteDelete(noteId: number, options?: AxiosRequestConfig) {
        return MlApiFp(this.configuration).deleteNoteMlNoteDelete(noteId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete Question
     * @param {number} questionId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MlApi
     */
    public deleteQuestionMlQuestionDelete(questionId: number, options?: AxiosRequestConfig) {
        return MlApiFp(this.configuration).deleteQuestionMlQuestionDelete(questionId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Edit Question
     * @param {QuestionEdit} questionEdit 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MlApi
     */
    public editQuestionMlQuestionPut(questionEdit: QuestionEdit, options?: AxiosRequestConfig) {
        return MlApiFp(this.configuration).editQuestionMlQuestionPut(questionEdit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Edit Sentence
     * @param {EmbeddedSentenceEdit} embeddedSentenceEdit 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MlApi
     */
    public editSentenceMlEditPut(embeddedSentenceEdit: EmbeddedSentenceEdit, options?: AxiosRequestConfig) {
        return MlApiFp(this.configuration).editSentenceMlEditPut(embeddedSentenceEdit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Embed Sentence
     * @param {EmbeddedSentencePost} embeddedSentencePost 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MlApi
     */
    public embedSentenceMlEmbedPost(embeddedSentencePost: EmbeddedSentencePost, options?: AxiosRequestConfig) {
        return MlApiFp(this.configuration).embedSentenceMlEmbedPost(embeddedSentencePost, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Search For Question
     * @param {string} searchKey 
     * @param {number} [resultRequest] 
     * @param {string | Array<string> | null} [stringArraystring] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MlApi
     */
    public searchForQuestionMlSearchQuestionGet(searchKey: string, resultRequest?: number, stringArraystring?: string | Array<string> | null, options?: AxiosRequestConfig) {
        return MlApiFp(this.configuration).searchForQuestionMlSearchQuestionGet(searchKey, resultRequest, stringArraystring, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Search For Value
     * @param {string} searchSentence 
     * @param {number} [resultRequest] 
     * @param {Array<string> | null} [requestBody] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MlApi
     */
    public searchForValueMlSearchNoteGet(searchSentence: string, resultRequest?: number, requestBody?: Array<string> | null, options?: AxiosRequestConfig) {
        return MlApiFp(this.configuration).searchForValueMlSearchNoteGet(searchSentence, resultRequest, requestBody, options).then((request) => request(this.axios, this.basePath));
    }
}



