from enum import Enum


class Topic(str, Enum):
    GENERAL = "general"
    ANATOMY = "anatomy"
    BIOCHEMISTRY = "biochemistry"
    GENETICS = "genetics"
    IMMUNOLOGY = "immunology"
    MICROBIOLOGY = "microbiology"
    PATHOLOGY = "pathology"
    ANESTHESIOLOGY = "anesthesiology"
    DERMATOLOGY = "dermatology"
    EMERGENCY = "emergency"
    HOSPICE = "hospice"
    CARDIOVASCULAR = "cardiovascular"
    GASTROENTEROLOGY = "gastroenterology"
    HEMATOLOGY = "hematology"
    ONCOLOGY = "oncology"
    NEPHROLOGY = "nephrology"
    INFECTIOUS_DISEASE = "infectious disease"
    RHEUMATOLOGY = "rheumatology"
    NEUROLOGY = "neurology"
    OBSTERICS = "obsterics"
    GYNECOLOGY = "gynecology"
    OPHTHALMOLOGY = "ophthalmology"
    ORTHOPAEDICS = "orthopaedics"
    OTOLARYNGOLOGY = "otolaryngology"
    PEDIATRICS = "pediatrics"
    PLASTICS = "plastics"
    PMR = "physical medicine and rehabilitation"
    PSYCHIATRY = "psychiatry"
    RADIOLOGY = "radiology"
    SURGERY = "surgery"
    UROLOGY = "urology"
